"http://unisonweb.org/2015-05-07/about.html"
"http://www.bigdatanews.com/profiles/blogs/introducing-the-pads-framework"
"https://www.packet.net/blog/coreos-and-the-the-future-of-the-internet/"
"http://www.tomjewett.com/dbdesign/dbdesign.php"
"https://www.massdrop.com/article/introduction-to-keyboard-programming"
"http://blog.paralleluniverse.co/2015/05/21/quasar-vs-akka/"
"http://synsem.com/SyncNotAsync/"
"http://www.datasciencecentral.com/profiles/blogs/latest-moocs-on-data-science"
"http://developer.marklogic.com/blog/data-integration-with-fields"
"http://restcookbook.com/"
"http://www.puppetcookbook.com/"
"https://nickdesaulniers.github.io/blog/2015/05/25/interpreter-compiler-jit/"
"http://lush.sourceforge.net/"
"http://www.infoq.com/news/2015/05/ioda-architecture"
"https://modulus.io/"

"http://www.sitepoint.com/future-programming-webassembly-life-after-javascript/"
"http://www.datasciencecentral.com/profiles/blogs/lambda-architecture-for-big-data-systems"
"http://www.javacodegeeks.com/2012/01/sharding-system-architecture-several.html"
"https://www.edx.org/school/iimbx"
"http://worrydream.com/dbx/"
"http://www.datasciencecentral.com/events/intro-to-apache-spark-free-webinar?xg_source=activity"
"https://www.google.com/design/icons/"
"http://ignorethecode.net/blog/2015/05/31/web_app_speed/"
"http://www.typesafe.com/resources/case-studies-and-stories/how-hootsuite-modernized-its-url-shortener"
"http://www.magicsplat.com/articles/oo.html"
"https://vimeo.com/123834986"
"https://www.youtube.com/watch?v=C8orjQLacTo"
"https://medium.com/@antoniogioia/all-you-need-to-know-about-dynamic-port-forwarding-using-ssh-socks5-proxy-and-a-linux-debian-vps-c4503921400f"
"https://blog.process-one.net/ejabberd-15-06/"
"http://nixos.org/"
"http://steshaw.org/plt/"
"https://vimeo.com/131192406"
"http://sysconfig.org.uk/two-factor-authentication-with-ssh.html"
"https://code.facebook.com/posts/964122680272229/web-performance-cache-efficiency-exercise/"
"http://theburningmonk.com/2015/06/all-the-fp-talks-at-ndc-oslo/"
"http://techblog.netflix.com/2015/06/nts-real-time-streaming-for-test.html"
"http://www.datasciencecentral.com/group/announcements/forum/topics/book-practical-machine-learning-a-new-look-at-anomaly-detection"
=======
"http://nixos.org/"
>>>>>>> Stashed changes
"http://unisonweb.org/2015-06-12/editing.html"
"http://www.javacodegeeks.com/2013/01/15-online-learning-websites-that-you-should-check-out.html"
"https://abdulyadi.wordpress.com/2015/06/02/which-replicated-tables-got-changes-in-bdr-replication/"
"https://2015.nosql-matters.org/bcn/call-for-papers/"
"http://bravenewgeek.com/distributed-systems-are-a-ux-problem/"
"https://snap.stanford.edu/data/"
<<<<<<< Updated upstream
"http://www.fefe.de/gatling/?ref=hn"
"https://queue.acm.org/detail.cfm?id=2611829"
"http://avoidwork.github.io/rozu/"
"http://www.cockroachlabs.com/blog/scaling-raft/"
"http://wryun.github.io/es-shell/"
=======
>>>>>>> Stashed changes
"http://labs.domipheus.com/blog/designing-a-cpu-in-vhdl-part-1-rationale-tools-method/"
"https://www.graylog.org/graylog-1-1-is-now-generally-available/"
"http://bravenewgeek.com/service-disoriented-architecture/"
"http://stackshare.io/wix/scaling-wix-to-60m-users---from-monolith-to-microservices"
"http://www.nytimes.com/2015/06/07/magazine/a-music-sharing-network-for-the-unconnected.html?_r=0"
"https://www.mapr.com/blog/apache-drill-essentials-new-hadoop-on-demand-training-course-now-available#.VXkfYbyli1E"
<<<<<<< Updated upstream
"https://www.youtube.com/watch?v=h36PGcA_8Cc&index=1&list=PLOU2XLYxmsIIxexEszFQujHy38pG4pIk0&linkId=14884224"
=======
"https://www.youtube.com/watch?v=h36PGcA_8Cc&index=1&list=PLOU2XLYxmsIIxexEszFQujHy38pG4pIk0&linkId=14884224"
>>>>>>> Stashed changes
