"BigData":{
		"Hadoop":[
			"http://saphanatutorial.com/hadoop-1-0-vs-hadoop-2-0/"
			"http://www.hadoop360.com/blog/hadoop-technology-stack"
			"http://blog.cloudera.com/blog/2015/03/understanding-hdfs-recovery-processes-part-2/?utm_content=buffera6755&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://www.hadoop360.com/xn/detail/6623215:BlogEntry:9496"
			"http://blog.cloudera.com/blog/2015/03/how-to-quickly-configure-kerberos-for-your-apache-hadoop-cluster/?utm_content=bufferc5978&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://www.slideshare.net/andreagioia/fast-data-platforms-hadoop-user-group-italy"
			"http://www.hadoop360.com/blog/spark-shark-and-mesos-data-analytics-stack",
			"http://www.hadoop360.com/blog/8-hadoop-articles-that-you-should-read"
			"http://vision.cloudera.com/data-governance-in-hadoop-part-2/?utm_source=twitterfeed&utm_medium=twitter"
		],

		"Spark":[
		"http://java.dzone.com/articles/big-data-processing-spark?utm_source=twitterfeed&utm_medium=twitter"
		"https://databricks.com/blog/2015/03/13/announcing-spark-1-3.html"
		"http://www.infoworld.com/article/2903432/application-development/spark-big-datas-brightest-star-needs-to-grow-up.html"
		"http://tech.marksblogg.com/recommendation-engine-spark-python.html"
		"http://www.informationweek.com/big-data/big-data-analytics/apache-spark-three-promising-use-cases/a/d-id/1319660?_mc=sm_iwk"
			"https://haifengl.wordpress.com/2014/09/07/big-data-analytics-shark-and-spark-sql/"
			"http://www.infoq.com/news/2015/03/pinterest-memsql-spark-streaming?utm_source=twitter&utm_medium=link&utm_content=pinterest+news&utm_campaign=calendar"
		],
		"Mesos":[
			"http://www.antonlindstrom.com/2015/03/29/introduction-to-apache-mesos.html"
			"http://www.javacodegeeks.com/2015/04/apache-mesos-marathon-and-java-ee.html",
		],
		"Mapr":[
			"https://www.mapr.com/blog/polyglot-data-management-big-data-everywhere-recap#.VQ0LIFmNDec"
			"https://www.mapr.com/resources/videos/apache-drill-redefining-sql-hadoop-0",
		]
		"ApacheDrill":[
			"http://drill.apache.org/blog/2015/03/31/drill-0.8-released/"
		],
		"ApacheKafka":[
			"https://engineering.linkedin.com/kafka/running-kafka-scale"
		]
		"Others":[
			"http://www.javacodegeeks.com/2013/07/mapreduce-algorithms-understanding-data-joins-part-1.html?utm_content=buffer5f298&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://www.efytimes.com/e1/fullnews.asp?edid=162753"
			"https://haifengl.wordpress.com/2014/08/18/big-data-analytics-mapreduce/"
			"http://www.datameer.com/blog/webinars/datameer-bigstep-big-data-analytics-for-your-department-now-not-in-months.html"
			"http://radar.oreilly.com/2015/04/a-real-time-processing-revival.html",
			"http://blogs.teradata.com/tdmo/best-practices-big-data-strategy-execution/?utm_source=twitter&utm_medium=earnedsocial&utm_campaign=blogs"
		]
	},