"BigData":{
		"Hadoop":[
			"http://hortonworks.com/blog/hortonworks-acquires-sequenceiq-to-provide-automated-deployment-of-hadoop-everywhere/"
			"http://www.datasciencecentral.com/profiles/blogs/hadoop-2-helps-systems-integration"
			"http://www.infoq.com/articles/Hadoop-Cluster"
			"http://blog.cloudera.com/blog/2015/01/how-to-deploy-apache-hadoop-clusters-like-a-boss/"
			"https://developer.rackspace.com/blog/monitoring-hadoop-with-rackspace-cloud-services/"
			"http://radar.oreilly.com/2015/02/processing-frameworks-for-hadoop.html"
			"http://blog.cloudera.com/blog/2015/02/understanding-hdfs-recovery-processes-part-1/"
			"https://districtdatalabs.silvrback.com/creating-a-hadoop-pseudo-distributed-environment"
			"http://engineering.viki.com/blog/2015/analytics-infrastracture-updates/"
			"http://saphanatutorial.com/hadoop-1-0-vs-hadoop-2-0/"
			"http://appaloud.com/splice-machine-takes-big-step-releasing-version-1-0-hadoop-rdbms/"
			"http://www.hadoop360.com/blog/hadoop-technology-stack"
			"http://blog.cloudera.com/blog/2015/03/understanding-hdfs-recovery-processes-part-2/.com&utm_campaign=buffer"
			"http://www.hadoop360.com/xn/detail/6623215:BlogEntry:9496"
			"http://blog.cloudera.com/blog/2015/03/how-to-quickly-configure-kerberos-for-your-apache-hadoop-cluster/.com&utm_campaign=buffer"
			"http://www.slideshare.net/andreagioia/fast-data-platforms-hadoop-user-group-italy"
			"http://www.hadoop360.com/blog/spark-shark-and-mesos-data-analytics-stack",
			"http://www.hadoop360.com/blog/8-hadoop-articles-that-you-should-read"
			"http://vision.cloudera.com/data-governance-in-hadoop-part-2/"
		],


		"Spark":[
			"http://www.enterpriseappstoday.com/data-management/is-apache-spark-enterprise-ready.html"
			"http://www.duchess-france.org/analyze-accelerometer-data-with-apache-spark-and-mllib/"
			"http://www.hadoop360.com/blog/spark-shark-and-mesos-data-analytics-stack"
			"https://databricks.com/blog/2015/04/13/deep-dive-into-spark-sqls-catalyst-optimizer.html"
			"http://blog.cloudera.com/blog/2015/03/how-to-tune-your-apache-spark-jobs-part-2/"
			"http://www.infoq.com/news/2015/03/pinterest-memsql-spark-streaming"
			"http://rnowling.github.io/spark/2015/04/07/multiuser-spark-mesos.html"
			"http://www.zdnet.com/article/sparks-success-overhyped-or-preordained/"
			"http://developerblog.redhat.com/2015/01/20/microservice-principles-and-immutability-demonstrated-with-apache-spark-and-cassandra/"
			"http://www.kennybastani.com/2015/01/categorical-pagerank-neo4j-spark.html"
			"http://blog.sematext.com/2015/01/21/spark-performance-monitoring-use-case/"
			"https://www.youtube.com/watch?v=z7bIt143smw"
			"http://blog.couchbase.com/introducing-the-couchbase-spark-connector"
			"http://www.cakesolutions.net/teamblogs/using-spark-to-analyse-akka-persistence-events-in-cassandra"
			"http://blog.cloudera.com/blog/2015/03/how-to-tune-your-apache-spark-jobs-part-1/"
			"http://java.dzone.com/articles/big-data-processing-spark"
			"https://databricks.com/blog/2015/03/13/announcing-spark-1-3.html"
			"http://www.infoworld.com/article/2903432/application-development/spark-big-datas-brightest-star-needs-to-grow-up.html"
			"http://tech.marksblogg.com/recommendation-engine-spark-python.html"
			"http://www.informationweek.com/big-data/big-data-analytics/apache-spark-three-promising-use-cases/a/d-id/1319660?_mc=sm_iwk"
			"https://haifengl.wordpress.com/2014/09/07/big-data-analytics-shark-and-spark-sql/"
			"http://www.infoq.com/news/2015/03/pinterest-memsql-spark-streaming+news&utm_campaign=calendar"
		],
		"Mesos":[
			"www.datasciencecentral.com/profiles/blogs/spark-shark-and-mesos-data-analytics-stack"
			"http://www.javacodegeeks.com/2014/01/getting-started-with-apache-mesos-and-apache-aurora-using-vagrant.html"
			"http://radar.oreilly.com/2015/02/a-tale-of-two-clusters-mesos-and-yarn.html"
			"http://www.antonlindstrom.com/2015/03/29/introduction-to-apache-mesos.html"
			"http://www.javacodegeeks.com/2015/04/apache-mesos-marathon-and-java-ee.html",
		],
		"Mapr":[
			"https://www.mapr.com/blog/4-critical-things-consider-when-building-hadoop-rfp#.VTHF8OSEi-k"
			"https://www.mapr.com/services/mapr-academy/big-data-hadoop-online-training"
			"https://www.mapr.com/blog/strategic-data-beyond-hadoop-and-big-data#.VSWDCuSEi-k"
			"https://www.mapr.com/blog/how-use-mapreduce-api"
			"https://www.mapr.com/blog/polyglot-data-management-big-data-everywhere-recap#.VQ0LIFmNDec"
			"https://www.mapr.com/resources/videos/apache-drill-redefining-sql-hadoop-0",
		]
		"ApacheDrill":[
			"https://www.youtube.com/watch?v=FkcegazNuio"
			"http://www.datasciencecentral.com/profiles/blogs/drill-data-with-apache-drill"
			"http://www.dbta.com/BigDataQuarterly/Articles/The-Importance-of-Apache-Drill-to-the-Big-Data-Ecosystem-103000.aspx"
			"http://drill.apache.org/blog/2015/03/31/drill-0.8-released/"
		],
		"ApacheKafka":[
			"http://blog.confluent.io/2015/02/25/stream-data-platform-1/"
			"http://java.dzone.com/articles/using-apache-kafka-integration"
			"http://blog.confluent.io/2015/04/07/hands-free-kafka-replication-a-lesson-in-operational-simplicity/"
			"http://svds.com/post/using-docker-build-data-acquisition-pipeline-kafka-and-hbase"
			"http://blog.cloudera.com/blog/2015/02/how-to-do-real-time-log-analytics-with-apache-kafka-cloudera-search-and-hue/"
			"https://databricks.com/blog/2015/03/30/improvements-to-kafka-integration-of-spark-streaming.html"
			"https://engineering.linkedin.com/kafka/running-kafka-scale"
		]
		"ApacheCamel":[
			"http://examples.javacodegeeks.com/core-java/apache-camel-hello-world-example/"
		]
		"Others":[

			"http://www.analyticbridge.com/profiles/blogs/what-mapreduce-can-t-do"
			"http://www.datasciencecentral.com/profiles/blogs/s3-instead-of-hdfs-with-hadoop"
			"http://www.bigdatanews.com/profiles/blogs/big-data-s-real-3vs"
			"http://www.vbprofiles.com/press_releases/55367cb8b4e919dc55000c5c"
			"http://www.hadoop360.com/blog/accumulo-sqrrl-nosql-secure-database"
			"http://blog.algorithmia.com/post/116365814879/how-machines-see-the-web-exploring-the-web"
			"http://www.datasciencecentral.com/profiles/blogs/the-7-most-unusual-applications-of-big-data-you-ve-ever-seen"
			"http://grigory.us/blog/rdbms-mapreduce/"
			"https://www.youtube.com/watch?v=kRjk_Xsf7t4"
			"http://www.hadoop360.com/blog/batch-vs-real-time-data-processing"
			"http://www.javacodegeeks.com/2013/07/mapreduce-algorithms-understanding-data-joins-part-1.html.com&utm_campaign=buffer"
			"http://www.efytimes.com/e1/fullnews.asp?edid=162753"
			"https://haifengl.wordpress.com/2014/08/18/big-data-analytics-mapreduce/"
			"http://www.datameer.com/blog/webinars/datameer-bigstep-big-data-analytics-for-your-department-now-not-in-months.html"
			"http://radar.oreilly.com/2015/04/a-real-time-processing-revival.html",
			"http://blogs.teradata.com/tdmo/best-practices-big-data-strategy-execution/"
			"http://blog.swiftype.com/building-an-asynchronous-api-to-improve-performance"
		]
	},