"CloudComputing":{
		"AWS":[
			"http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumes.html?adbsc=docs_20150403_42955476&adbid=583799107174604804&adbpl=tw&adbpr=66780587"
			"http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_agent.html?adbsc=docs_20150325_42653946&adbid=580761172456001536&adbpl=tw&adbpr=66780587#private-auth"
			"http://java.dzone.com/articles/working-amazon-s3-%E2%80%93-part-i.com&utm_campaign=buffer",

		],
		"Heroku":[
			"http://purple.herokuapp.com/"
		]
		"Docker":[
			"http://blog.docker.com/2015/03/docker-tutorial-1-installing-docker/"
			"http://blog.rodolfocarvalho.net/2015/02/falcon-django-pypy-docker.html?m=1"
			"https://github.com/docker-library/pypy/blob/master/2/Dockerfile"
			"http://blog.earlyclaim.com/get-your-javascript-website-perfectly-crawled-with-docker/"
			"https://www.joyent.com/"
			"http://www.infoworld.com/article/2900832/virtualization/joyents-no-vm-docker-host-deploys-containers-on-bare-metal.html"
			"http://blog.giantswarm.io/how-docker-made-coding-and-testing-new-projects-fun-and-accessible"
			"https://www.joyent.com/blog/triton-docker-and-the-best-of-all-worlds"
			"http://www.infoq.com/news/2015/03/gupta-javaee-docker-kubernetes"
			"http://blog.codeship.com/using-docker-to-parallelize-rails-tests/"
			"https://github.com/chanezon/docker-tips/blob/master/docker-machine-docker-latest.md",
			"https://blog.docker.com/2015/04/announcing-webhook-respository-subscriptions/",
			"http://blog.thekingshotts.com/2015/04/02/getting-started-with-docker/",
			"https://www.youtube.com/watch?v=bV5vbNK3Uhw&list=PLkA60AVN3hh_6cAz8TUGtkYbJSL2bdZ4h",
			"https://www.youtube.com/watch?v=wLdm4MnnxoA&feature=youtu.be",
			"https://blog.docker.com/2015/04/docker-tutorial-3-fun-with-volumes/",
			"https://blog.docker.com/2015/03/docker-tutorial-2-docker-run-command-basics/"
			"https://github.com/msanand/docker-workflow.git",
			"http://www.infoq.com/interviews/Luke-Marsden-ZFS-Docker"
			"https://blog.docker.com/2015/03/videos-from-the-biggest-docker-meetup-ever-clocker-storage-drivers-docker-on-the-desktop-powerstrip/",
			"http://blog.heavybit.com/blog/2015/3/23/dockermeetup"
"http://www.javacodegeeks.com/2015/03/docker-machine-to-setup-docker-host.html"
"https://blog.docker.com/2015/03/tiny-docker-operating-systems/"
"https://www.joyent.com/blog/container-service-preview"
			"https://zwischenzugs.wordpress.com/2015/03/14/docker-in-practice-a-guide-for-engineers/"
		],
		"Openstack":[],
		"Others":[
			"http://www.dataplumbing.com/blog/example-of-architecture-for-aaas-analytics-as-a-service"
			"http://hwit.org/scalable-design-is-within-grasp.html"
		]
	},