"CloudComputing":{
		"AWS":[
			"https://aws.amazon.com/blogs/aws/amazon-machine-learning-make-data-driven-decisions-at-scale/"
			"http://aws.amazon.com/efs/"
			"http://techcrunch.com/2015/04/09/amazon-launches-new-efs-file-storage-service-for-ec2"
			"http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumes.html?adbsc=docs_20150403_42955476&adbid=583799107174604804&adbpl=tw&adbpr=66780587"
			"http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_agent.html?adbsc=docs_20150325_42653946&adbid=580761172456001536&adbpl=tw&adbpr=66780587#private-auth"
			"http://java.dzone.com/articles/working-amazon-s3-%E2%80%93-part-i.com&utm_campaign=buffer",

		],
		"Heroku":[
			"http://purple.herokuapp.com/"
		]
		"Docker":[
			"http://www.javacodegeeks.com/2014/10/getting-started-with-docker.html"
			"http://linoxide.com/linux-how-to/important-docker-commands/"
			"https://www.airpair.com/node.js/posts/getting-started-with-docker-for-the-nodejs-dev"
			"http://anandmanisankar.com/posts/docker-container-nginx-node-redis-example/"
			"http://azure.microsoft.com/blog/2015/04/08/microsoft-unveils-new-container-technologies-for-the-next-generation-cloud/"
			"https://blog.docker.com/2015/04/docker-tutorial-4-more-run-with-a-couple-of-extra-goodies/"
			"http://blog.doordash.com/post/115409532041/migrating-from-heroku-to-aws-using-docker"
			"http://java.dzone.com/articles/logging-docker-what-you-need"
			"http://blog.hypriot.com/post/docker-compose-nodejs-haproxy"
			"http://blog.viktorpetersson.com/post/115562026784/using-cgroups-with-docker-on-ubuntu-14-04"
			"http://blog.doordash.com/post/115409532041/migrating-from-heroku-to-aws-using-docker"
			"http://www.javacodegeeks.com/2015/04/httpwww-radcortez-comget-into-docker.html"
			"http://blog.docker.com/2015/03/docker-tutorial-1-installing-docker/"
			"http://blog.rodolfocarvalho.net/2015/02/falcon-django-pypy-docker.html?m=1"
			"https://github.com/docker-library/pypy/blob/master/2/Dockerfile"
			"http://blog.earlyclaim.com/get-your-javascript-website-perfectly-crawled-with-docker/"
			"https://www.joyent.com/"
			"http://www.infoworld.com/article/2900832/virtualization/joyents-no-vm-docker-host-deploys-containers-on-bare-metal.html"
			"http://blog.giantswarm.io/how-docker-made-coding-and-testing-new-projects-fun-and-accessible"
			"https://www.joyent.com/blog/triton-docker-and-the-best-of-all-worlds"
			"http://www.infoq.com/news/2015/03/gupta-javaee-docker-kubernetes"
			"http://blog.codeship.com/using-docker-to-parallelize-rails-tests/"
			"https://github.com/chanezon/docker-tips/blob/master/docker-machine-docker-latest.md",
			"https://blog.docker.com/2015/04/announcing-webhook-respository-subscriptions/",
			"http://blog.thekingshotts.com/2015/04/02/getting-started-with-docker/",
			"https://www.youtube.com/watch?v=bV5vbNK3Uhw&list=PLkA60AVN3hh_6cAz8TUGtkYbJSL2bdZ4h",
			"https://www.youtube.com/watch?v=wLdm4MnnxoA&feature=youtu.be",
			"https://blog.docker.com/2015/04/docker-tutorial-3-fun-with-volumes/",
			"https://blog.docker.com/2015/03/docker-tutorial-2-docker-run-command-basics/"
			"https://github.com/msanand/docker-workflow.git",
			"http://www.infoq.com/interviews/Luke-Marsden-ZFS-Docker"
			"https://blog.docker.com/2015/03/videos-from-the-biggest-docker-meetup-ever-clocker-storage-drivers-docker-on-the-desktop-powerstrip/",
			"http://blog.heavybit.com/blog/2015/3/23/dockermeetup"
			"http://www.javacodegeeks.com/2015/03/docker-machine-to-setup-docker-host.html"
			"https://blog.docker.com/2015/03/tiny-docker-operating-systems/"
			"https://www.joyent.com/blog/container-service-preview"
			"https://zwischenzugs.wordpress.com/2015/03/14/docker-in-practice-a-guide-for-engineers/"
			"http://www.conductor.com/nightlight/running-selenium-grid-using-docker-compose/"
			"http://java.dzone.com/articles/docker-how-jboss-integration"
		],
		"Openstack":[],
		"Others":[
			"http://techcrunch.com/2015/04/11/whatever-happened-to-paas"
			"http://appaloud.com/cloudian-storage-scaled-for-big-data/"
			"http://www.datasciencecentral.com/profiles/blogs/6-cloud-based-machine-learning-services?xg_source=activity"
			"http://www.dataplumbing.com/blog/example-of-architecture-for-aaas-analytics-as-a-service"
			"http://hwit.org/scalable-design-is-within-grasp.html"
		]
	},