"DataScience":[
	"http://www.datavizualization.com/blog/using-decision-trees-in-evidence-based-medicine"
	"http://www.datasciencecentral.com/profiles/blogs/an-introduction-to-social-network-analysis",
	"https://timdettmers.wordpress.com/2015/03/26/convolution-deep-learning/"
	"https://jessesw.com/Data-Science-Skills/",
	"http://blog.sense.io/introducing-sense-a-platform-for-data-science/"
	"https://outlookzen.wordpress.com/2015/03/15/life-lessons-from-machine-learning/"
	"http://www.analyticbridge.com/forum/topics/semi-supervised-learnig-knn-kmeans"
	"http://www.analyticbridge.com/profiles/blogs/data-analysis-beginners"
	"http://willwhitney.github.io/dc-ign/www/"
	"http://www.datavizualization.com/blog/why-is-data-now-called-big-part-1"
	"http://www.datasciencecentral.com/profiles/blogs/tutorial-how-to-detect-spurious-correlations-and-how-to-find-the-"
	"http://www.datasciencecentral.com/profiles/blogs/how-to-become-a-data-scientist-for-free"
	"http://tomtunguz.com/data-science-demystified/"
	""
	"http://www.datasciencecentral.com/profiles/blogs/data-scientist-vs-statistician"
	"http://www.bigdatanews.com/profiles/blogs/introducing-the-pads-framework"
	"http://www.datasciencecentral.com/profiles/blogs/big-data-not-so-big-parallel-thread-processing-in-sas"
	"http://www.forbes.com/sites/louiscolumbus/2015/03/15/data-analytics-dominates-enterprises-spending-plans-for-2015/"
	"http://sebastianraschka.com/Articles/2015_singlelayer_neurons.html.com&utm_campaign=buffer"
	"http://vaidehijoshi.github.io/blog/2015/03/24/a-machine-state-of-mind-part-2-implementing-state-machines/"
	"http://careers.analytictalent.com/jobs/data-manager-chicago-illinois-60611-76409893-d?contextType=rss",
	"http://www.statslife.org.uk/the-statistics-dictionary/2148-han-solo-and-bayesian-priors",
	"http://quantombone.blogspot.com/2015/03/deep-learning-vs-machine-learning-vs.html"
	"http://blog.yhathq.com/posts/measuring-model-performance-1.html.com&utm_campaign=buffer"
	"http://vaidehijoshi.github.io/blog/2015/03/24/a-machine-state-of-mind-part-2-implementing-state-machines/",
	"http://www.machinalis.com/blog/rt-notifications-gevent-gis/.com&utm_campaign=buffer"
],