"Database":{
		"SQL":[
		"MySQL":[
			"http://use-the-index-luke.com/blog/2014-04-01/thank-you-mysql-we-will-miss-you"
		],
		"Postgresql":[
			"http://developer.olery.com/blog/goodbye-mongodb-hello-postgresql/"
			"https://blog.compose.io/is-postgresql-your-next-json-database/?utm_content=buffer2dc13&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://engineering.tilt.com/7-postgresql-data-migration-hacks/"
		"http://developers.slashdot.org/story/15/03/19/1930226/why-i-choose-postgresql-over-mysqlmariadb?utm_source=slashdot&utm_medium=twitter"
			"http://www.citusdata.com/blog/21-jason/139-announcing-pg-shard-1-1"
			"http://rajeevrastogi.blogspot.com/2015/03/overview-of-postgresql-sql-engine.html"
			"http://www.citusdata.com/blog/14-marco/122-pgconf-russia-talk-on-pg-shard"
			"http://hlinnaka.iki.fi/2015/03/23/pg_rewind-in-postgresql-9-5/"
			"http://news.dice.com/2015/03/19/why-i-choose-postgresql-over-mysqlmariadb/"
			"http://thebuild.com/blog/2015/03/28/postgresql-and-json-2015/"
			"http://blog.honeybadger.io/using-temporary-tables-in-postgresql-with-rails/"
			"http://www.infoq.com/news/2015/04/Postgresql-JSON-Datastore?utm_campaign=infoq_content&utm_source=infoq&utm_medium=feed&utm_term=global",
			"http://8kb.co.uk/blog/2015/04/02/being-cavalier-with-slony-nodes-and-pg_dumppg_restore/",
		],
		"Oracle":[],
		"SQLServer":[]
	],
	"NoSQL":{
		"RethinkDB":[
			"http://blog.workshape.io/we-use-rethinkdb-at-workshapeio/"
			"http://rethinkdb.com/blog/realtime-cluster-monitoring/"
			"http://rethinkdb.com/blog/2.0-release-candidate/"
		]
		"FoundationDB":[
			"https://foundationdb.com/key-value-store/versus"
		],
		"VoltDB":[
			"http://voltdb.com/blog/lambda-complexity-why-fast-data-needs-new-thinking"
			"http://learn.voltdb.com/WRFull360.html"
		]
		"Mongodb":[
			"https://www.mongodb.com/blog/post/creating-single-view-part-2-schema-development"
			"http://www.mongodb.com/webinar/Fast-Querying-Indexing-Strategies-to-Optimize-Performance"
			"http://www.prnewswire.com/news-releases/mongodb-30-with-wired-tiger-new-benchmark-measures-performance-vs-couchbase-server-302-300053144.html"
			"https://databricks.com/blog/2015/03/20/using-mongodb-with-spark.html"
			"http://use-the-index-luke.com/blog/2013-10-01/mysql-is-to-sql-like-mongodb-to-nosql"
			"http://www.mongodb.com/blog/post/creating-single-view-part-3-data-design-and-loading-strategies"
			"http://www.mongodb.com/blog/post/announcing-next-generation-drivers-mongodb"
			"http://www.mongodb.com/blog/post/creating-single-view-part-3-data-design-and-loading-strategies?utm_content=buffer1d3ea&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"https://intellipaat.com/jaspersoft-mongodb-training/"
			"https://www.mongodb.com/blog/post/server-selection-next-generation-mongodb-drivers"
		],
		"CouchBase":[
			"http://www.dbta.com/Editorial/News-Flashes/Uncovering-the-Advantages-of--N1QL-Couchbases-Query-Language-102267.aspx"
			"http://blog.couchbase.com/introducing-the-couchbase-kafka-connector"
			"http://blog.couchbase.com/hortonworks-and-couchbase-nosql-fueled-hadoop"
			"http://www.informationweek.com/big-data/big-data-analytics/couchbase-claims-performance-gains-against-nosql-rivals/d/d-id/1319572"
			"http://blog.couchbase.com/introducing-the-couchbase-spark-connector"
			"http://www.dbta.com/Editorial/News-Flashes/Couchbase-Server-40-to-Advance-Application-Performance-through-Multi-Dimensional-Scaling-102807.aspx"
			"http://www.datacenterknowledge.com/archives/2015/03/23/couchbase-rethinks-nosql-database-architecture/"
			"http://www.javacodegeeks.com/2013/10/pagination-with-couchbase.html?utm_content=buffer83493&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://www.v3.co.uk/v3-uk/news/2401197/ryanair-picks-couchbase-nosql-database-for-mobile-reservations-app"
			"http://www.techtimes.com/articles/41559/20150324/database-startup-couchbase-introduces-multi-dimensional-scaling.htm"
			"http://latestbuilds.hq.couchbase.com/"
			"https://forums.couchbase.com/t/rpm-location-change-breaks-couchbase-server-2-2-0-download-for-centos-cookbook/1921/4"
			"http://packages.couchbase.com/releases/2.2.0/couchbase-server-community_2.2.0_x86_64.rpm"
			"https://github.com/couchbaselabs/vagrants/blob/master/Vagrantfile"
			"http://builder.hq.couchbase.com/",
			"http://blog.couchbase.com/mongodb-rules-single-node-deployments",
			"http://blog.couchbase.com/mongodb-rules-single-node-deployments",
		],
		"Redis":[
			"http://fr.slideshare.net/itamarhaber/benchmarking-redis-by-itself-and-versus-other-nosql-databases"
			"http://antirez.com/news/88"
			"http://bencane.com/2013/11/12/installing-redis-and-setting-up-master-slave-replication/"
			"https://everystack.io/#!/catalog/components/redis-py"
			"http://jamesls.com/writing-redis-in-python-with-asyncio-part-1.html?utm_content=buffer5337e&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"https://github.com/no13bus/redispapa?utm_content=buffer949dc&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer",

		],
		"Neo4j":[
			"http://xnlogic.com/xn-framework"
			"http://snip.ly/uS8Q?utm_content=buffer2dbbf&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer#http://blog.diatomenterprises.com/rails-and-neo4j/?utm_content=buffer13ddd&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"https://www.airpair.com/neo4j/posts/modelling-game-economy-with-neo4j"
			"http://www.kennybastani.com/2015/03/spark-neo4j-tutorial-docker.html?utm_content=bufferca842&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://blog.diatomenterprises.com/rails-and-neo4j/"
			"http://neo4j.com/blog/announcing-spring-data-neo4j-4-0/"
			"http://neo4j.com/blog/neo4j-2-2-0-scalability-performance/"
			"http://www.infoq.com/presentations/neo4j-java-heap-analysis?utm_content=buffer349a0&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer",
			"http://neo4jrb.io/blog/2015/03/31/neo4j-auth-in-neo4jrb.html",
			"http://neo4j.com/blog/due-ceo-demand-neo4j-2-2-features-ascii-art-graph-browser/",
			"http://www.markhneedham.com/blog/2015/04/01/neo4j-cypher-building-the-query-for-a-movies-profile-page/"
		],
		"Cassandra":[
			"https://www.youtube.com/watch?t=30&v=eqOPn5EtR7Q&utm_content=bufferc4c9d&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
		],
		"CouchDB":[
			"http://blog.couchdb.org/2015/04/02/couchdb-weekly-news-april-02-2015/"
		]
		"Hbase":[],
		"Riak":[
			"http://www.aosabook.org/en/riak.html"
			"https://kar.kent.ac.uk/30616/1/CEFP.pdf"
		],
		"Sphinx":[
			"http://sphinxsearch.com/blog/2015/03/11/sphinx-2-2-8-release/"
		]
		"Solr":[
			"http://recology.info/2015/03/faster-solr/"
		]
		"ElastickSearch":[
			"http://blog.pluralsight.com/elasticsearch-and-sql-server"
			"https://www.elastic.co/blog/elasticsearch-1-5-0-released"
		]

		"Others":[
			"http://blog.parsely.com/post/1691/lucene/"
			"https://everystack.io/#!/catalog/components/arangodb"
			"http://rightrelevance.com/?q=tab_type%3D2%26searchType%3Dfeeds%26start%3D0%26rows%3D30%26location%3D%26isPerson%3D%26articleId%3D885533e22de1cf4099a39ff770c542b8b4947c62%26value%3Dnosql%26taccount%3Dnosqlrr%26topic%3Dnosql"
			"http://rightrelevance.com/?q=tab_type%3D2%26searchType%3Dfeeds%26start%3D0%26rows%3D30%26location%3D%26isPerson%3D%26articleId%3D6e79a0196409a6c7c62ace2d06d37dcb33a0530f%26value%3Dnosql%26taccount%3Dnosqlrr%26topic%3Dnosql"
			"http://rightrelevance.com/?q=tab_type%3D2%26searchType%3Dfeeds%26start%3D0%26rows%3D30%26location%3D%26isPerson%3D%26articleId%3D679c8ba72061a6ebe3b4f5eab20a256289a13688%26value%3Dnosql%26taccount%3Dnosqlrr%26topic%3Dnosql"
			"http://www.ashnik.com/achieving-scalability-of-nosql-and-complexity-of-sql/"
			"http://www.metascale.com/company/big-data-careers/281-nosql-database-administrator.html"
			"http://rightrelevance.com/?q=tab_type%3D2%26searchType%3Dfeeds%26start%3D0%26rows%3D30%26location%3D%26isPerson%3D%26articleId%3D0fe10dc7de50c347036b50fc246c0badd2f80462%26value%3Dnosql%26taccount%3Dnosqlrr%26topic%3Dnosql"
			"http://planetnosql.blogspot.com/2015/03/query-planning-in-n1ql-sql-for-documents.html"
		]
	},
	"Others":[
		"http://blog.infoadvisors.com/index.php/2015/03/10/7-databases-in-70-minutes/"
		"http://blog.confluent.io/2015/03/04/turning-the-database-inside-out-with-apache-samza/"
	"https://www.pinterest.com/pin/473370610808082933/"
		"http://use-the-index-luke.com/blog/2013-10-01/mysql-is-to-sql-like-mongodb-to-nosql"
		"http://blog.dancrisan.com/intro-to-database-systems-indexing"
		"http://www.datasciencecentral.com/forum/topics/sql-to-nosql-translator"
		"http://blog.zerodb.io/hello-world-zerodb-here/"
		"http://www.infoq.com/vendorcontent/show.action?vcr=3117"
		"http://www.javacodegeeks.com/2013/10/the-10-most-popular-db-engines-sql-and-nosql.html?utm_content=bufferaeccb&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
		"http://venturebeat.com/2015/03/23/nosql-software-player-couchbase-will-launch-sql-for-documents-this-summer/"
		"https://www.linkedin.com/pulse/nosql-smackdown-couchbase-dominates-mongodb-benchmark-kurt-cagle"
		"http://www.datasciencecentral.com/profiles/blogs/lesson-4-features-common-to-most-nosql-newsql-databases",
		"http://www.aptuz.com/blog/is-postgres-nosql-database-better-than-mongodb/"
	]