"Devops":{
		"Apache":[],
		"Nginx":[
			"http://blog.victorquinn.com/nginx-as-a-spdy-reverse-proxy-passthrough?utm_source=nodeweekly&utm_medium=email"
			"http://academy.javacodegeeks.com/news/nginx-ssl-configuration-guide/"
			"http://nginx.com/solutions/load-balancing/",
			"http://code.tutsplus.com/articles/nginx-guide-essentials--cms-22880",
			"http://code.tutsplus.com/articles/nginx-guide-introduction--cms-21877"
		],
		"LightHttp":[],
		"Ansible":[
			"http://www.ansible.com/get-started+Tweet&utm_content=13496145&utm_medium=social&utm_source=twitter"
			"http://www.ansible.com/blog/ansible-fundamentals-webinar+Tweet&utm_content=13434856&utm_medium=social&utm_source=twitter"
			"http://www.ansible.com/how-ansible-works+Tweet&utm_content=13436951&utm_medium=social&utm_source=twitter",
			"http://www.ansible.com/docker+Tweet&utm_content=13383083&utm_medium=social&utm_source=twitter",
			"http://www.ansible.com/blog/ansible-fundamentals-webinar+Tweet&utm_content=13434861&utm_medium=social&utm_source=twitter",
			"http://www.ansible.com/blog/ansible-simplicity-keeps-shining+Tweet&utm_content=13435081&utm_medium=social&utm_source=twitter",
		],
		"Puppet":[
			"https://puppetlabs.com/blog/release-candidate-open-source-puppet-4.0?ls=social-media&ccn=twitter-product-20150318&cid=701G0000000F68P"
		],
		"Chef":[
			"https://www.chef.io/blog/2015/03/23/chef-client-12-1-2-released/"
			"http://www.flexiant.com/2015/03/13/learn-how-to-use-chef-on-any-cloud-today/"
			"https://learn.chef.io/learn-the-basics/rhel/get-set-up/"
			"https://docs.chef.io/#chef-dk-title"
			"http://devops.com/blogs/automation-provisioning-configuration-management-chef/"
		],
		"SaltStack":[]
	},