"DistributeSystem":{
		"AMQP":[],
		"RabbitMQ":[
			"http://java.dzone.com/articles/getting-notified-about"
			"https://devcenter.heroku.com/articles/asynchronous-web-worker-model-using-rabbitmq-in-node"
			"https://ilikerabbits.com/"
		],
		"ZeroMQ":[],
		"IronMQ":[
			"http://www.iron.io/rabbitmq"
		]
	},