"Erlang":[
		"http://erlangcentral.org/other-erldocs-alpha/#.VR1ZsMuEi-k",
		"https://www.youtube.com/playlist?list=PLWbHc_FXPo2h0sJW6X2RZDtT1ndw6KKpQ&app=desktop",
		"https://www.youtube.com/watch?v=uwpakTIg9r8",
		"https://www.youtube.com/watch?v=XpfGptXxdRY",
		"https://www.youtube.com/watch?v=GO_97_6w5lU"
		"https://gist.github.com/wardbekker/6876d1ed13eb40a47b55"
		"https://everystack.io/#!/catalog/components/mochiweb"
		"http://www.infoq.com/presentations/erlang-http-connections"
		"https://www.airpair.com/erlang/posts/solving-the-stable-marriage-problem-with-erlang?utm_term=marriage-problem-erlang&utm_content=buffer7a489&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
		"https://medium.com/@jlouis666/solving-the-go-challenge-1-in-erlang-8b1e0a0a5044"
		"http://www.ibm.com/developerworks/library/os-erlang1/"
		"http://stefanalfbo.github.io/blog/2013/04/23/erlang-shell-cheat-sheet/"
		"http://aerosol.github.io/anxibits/vim-as-your-erlang-ide/"
"https://navaspot.wordpress.com/2015/03/15/erlang-day1/"
		"https://medium.com/@jlouis666/solving-the-go-challenge-1-in-erlang-8b1e0a0a5044?source=tw-725a20c9f371-1426783051509"
		"http://roberto-aloi.com/erlang/notes-on-erlang-quickcheck-part-2/"
		"http://www.information-age.com/technology/applications-and-development/123459196/why-bet365-swapped-java-erlang"
		"http://erlangcentral.org/erlang-factory-sf-bay-2015-christopher-meiklejohn-distributed-eventually-consistent-computations/#.VRWVP8tQu-k"
	],