"Github":[
		"https://github.com/telefonicaid/di-py?utm_content=buffera2303&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer",
		"https://github.com/dabeaz/me-al",
		"http://asvd.github.io/syncscroll/"
		"https://github.com/kolodny/jsan"
		"https://github.com/gerryyang"
		"https://github.com/xyproto/algernon"
		"https://git-lfs.github.com/"
	],