{"Golang":[
	"http://golanggo.com/post/115334564374/how-to-do-stream-multiplexing-in-go",
	"http://golanggo.com/post/115333889744/quick-and-dirty-guide-to-deploying-go-apps",
	"https://www.kaihag.com/https-and-go/"
	"http://openmymind.net/Golangs-Error-Handling-Good-And-Bad/"
	"https://www.youtube.com/watch?v=gRpUfjTwSOo"
	"https://www.hakkalabs.co/articles/getting-started-gopherjs"
	"http://biasedbit.com/blog/golang-custom-transports/"
	"http://www.smartjava.org/content/using-go-build-rest-service-top-mongodb"
	"http://sinmetal-slide.appspot.com/2014/gocon1130/gaego.slide#1"
	"http://blog.altoros.com/golang-internals-part-2-diving-into-the-go-compiler.html"
	"https://www.voxxed.com/blog/2015/03/why-go-resonates-with-bdd-creator-dan-north/"
	"http://www.cs.cornell.edu/home/rvr/papers/flowgossip.pdf"
	"https://www.kaihag.com/external-assets-working-directories-and-go/"
	"https://www.cs.cornell.edu/projects/ladis2009/papers/lakshman-ladis2009.pdf"
	"https://blog.compose.io/go-rethinkdb-and-changefeeds-part-2"
	"https://blog.compose.io/go-rethinkdb-and-change-feeds-part-1",
	"http://mkaczanowski.com/golang-build-dynamic-dns-service-go/"
	"http://java.dzone.com/articles/exploring-go-template-engine"
	"http://blog.scalingo.com/post/105010314493/writing-a-replacement-to-openssh-using-go-2-2"
	"http://blog.scalingo.com/post/104426674353/writing-a-replacement-to-openssh-using-go-1-2"
	"https://www.hakkalabs.co/articles/make-it-feel-fast-using-groupcache-library-go"
	"http://soryy.com/blog/2014/common-mistakes-with-go-lang/"
}