"HTML":[
		"http://www.gajotres.net/best-html5-mobile-app-frameworks-supersonic/"
		"https://github.com/cloudant-labs/location-tracker-couchapp/blob/master/tutorial/tutorial.adoc"
		"http://www.webcodegeeks.com/html5/html5-navigation-bar-example/"
		"http://www.webcodegeeks.com/html5/html5-local-storage-example/"
		"http://www.infoq.com/news/2015/03/html6-without-javascript"
		"http://www.webcodegeeks.com/html5/html5-file-upload-example/"
		"http://www.webcodegeeks.com/html5/html5-websocket-example/"
	],