"InternetofThing":{
		"Microservice":[
			"http://pivotallabs.com/how-to-talk-to-your-friends-about-microservices/"
			"http://ruslanspivak.com/lsbaws-part1/"
			"http://www.infoq.com/news/2015/03/qcon-microservices-architecture"
			"http://www.infoworld.com/article/2903144/application-development/how-to-succeed-with-microservices-architecture.html"
			"http://java.dzone.com/articles/performance-issue"
			"http://www.infoq.com/interviews/rebecca-parsons-qcon-2015"
		],
		"Others":[
			"http://planetcassandra.org/blog/i2o-water-the-internet-of-things-and-cassandra/"
			"http://shop.oreilly.com/product/0636920040682.do"
			"http://www.thingstud.io/"
			"http://www.zdnet.com/article/ten-examples-of-iot-and-big-data-working-well-together/"
			"http://www.informationweek.com/wireless-infrastructure/iot-standardization-why-the-network-matters/a/d-id/1319418?_mc=sm_iwk"
		]
	},