"Javascript":{
		"Angular":[
			"https://medium.com/@KamilLelonek/angularjs-and-scope-apply-best-practices-d07353175024"
			"https://medium.com/@tomastrajan/component-paradigm-cf32e94ba78b"
			"http://eisenbergeffect.bluespire.com/aurelia-angular-2-0-code-side-by-side-part-2/"
			"http://www.encodedna.com/angularjs/tutorial/format-text-using-angularjs-currency-filter.htm"
			"http://blog.crowdint.com/2015/03/18/angularjs-providers-under-the-hood.html?utm_source=blogpost&utm_medium=reddit&utm_campaign=angujarjsproviders-150318"
			"http://www.htmlxprs.com/post/54/creating-a-super-simple-todo-app-using-angular-2-tutorial"
			"http://victorsavkin.com/post/114168430846/two-phases-of-angular-2-applications"
			"http://angularjs.blogspot.com/2015/03/forms-in-angular-2.html"
			"http://www.webcodegeeks.com/javascript/angular-js/interception-using-decorator-and-lazy-loading-with-angularjs/?utm_content=buffer60f40&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"https://www.airpair.com/angularjs/posts/ngmodeloptions-total-model-control?utm_source=angularjobs&utm_medium=angularjobs&utm_campaign=angularjobs"
			"http://www.jackyen.com/unit-test-a-controller-in-angularjs/"
			"https://angular.io/features.html"
			"https://stormpath.com/blog/angular-node-15-minutes/?utm_content=buffer36486&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://www.ciappara.com/2015/03/20/convert-json-object-from-angularjs-to-class-object-in-webapi/"
			"https://css-tricks.com/using-angularjs-for-data-visualisations/?utm_content=buffere8fc7&utm_medium=social&utm_source=twitter.com&utm_campaign=update"
			"http://www.webcodegeeks.com/javascript/angular-js/angular-js-routing-example/?utm_content=bufferf20f1&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://www.jackyen.com/how-to-unit-test-an-angular-application-service-with-requests-to-backend/"
			"http://www.aurorasolutions.io/step-by-step-guide-to-configure-angular-routing-using-angular-route/"
			"http://www.aurorasolutions.io/angularjs-cross-component-communication/"
			"http://frontendcollisionblog.com/angular_init/",
			"https://www.airpair.com/angularjs/posts/angularjs-promises?utm_source=angularjobs&utm_medium=angularjobs&utm_campaign=angularjobs"
			"http://blog.ionic.io/angular-2-series-introduction/",
			"https://www.airpair.com/angularjs/posts/angularjs-promises?utm_source=angularjobs&utm_medium=angularjobs&utm_campaign=angularjobs"
			"https://medium.com/@TK_CodeBear/getting-started-with-angular-part-1-bd448458566e",
			"https://docs.google.com/document/d/1M9FmT05Q6qpsjgvH1XvCm840yn2eWEg0PMskSQz7k4E/preview?sle=true",
			"http://trendytechhub.blogspot.com/2015/02/how-to-build-single-page-application.html",
			"http://dailyjs.com/2015/03/31/angular-grid-react-native/",
			"https://devcenter.appery.io/tutorials/angularjs/bootstrap/",
			"http://jaysoo.ca/2015/03/30/container-component-pattern-in-angular-1/",
			"http://conceptf1.blogspot.com/p/learning-angularjs.html",
			"http://jpeyatt.com/angularjs-ui-bootstrap-modals/"
			"http://aakilfernandes.github.io/angular-scopelogger/"
			"http://victorsavkin.com/post/114050927521/two-phases-of-angular-2-applications"
			"http://www.zainabed.com/2015/03/angularjs-tutorials-bootstrap.html"
			"https://blog.codecentric.de/en/2015/03/five-ways-to-write-better-angular-services/"
			"http://www.angularjsbook.com/angular-basics/chapters/basics/"
			"http://www.pro-tekconsulting.com/blog/advancing-from-jquery-to-angularjs/"
			"https://blog.nraboy.com/2015/03/using-oauth-2-0-in-your-web-browser-with-angularjs/?utm_content=buffer6b288&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://blog.carbonfive.com/2015/03/25/communication-between-collaborating-directives-in-angular/"
			"https://www.airpair.com/javascript/posts/build-a-realtime-sms-call-center-with-data-mcfly-and-twilio"
			"http://www.webcodegeeks.com/javascript/angular-js/learning-angular-set-language-culture-ui-displayed/"
			"https://medium.com/angularjs-meetup-south-london/angular-new-router-preview-8002340e5427"
			"https://github.com/swirlycheetah/generator-angular2"
			"http://blog.mgechev.com/2015/03/09/build-learn-your-own-light-lightweight-angularjs/#hnhttp://blog.mgechev.com/2015/03/09/build-learn-your-own-light-lightweight-angularjs/#hn"
			"https://www.airpair.com/pubnub/posts/realtime-angularjs-pubsub-messaging-using-pubnub1?utm_source=angularjobs&utm_medium=angularjobs&utm_campaign=angularjobs"
		],
		"JXCore":[
			"http://www.goland.org/jxcore/"
		]
		"Nodejs":[
			"http://code.tutsplus.com/tutorials/nodejs-succinctly-arrays--cms-23291"
			"http://omarfouad.com/blog/2015/03/21/advanced-angularjs-structure-with-gulp-node-and-browserify/?utm_content=buffer9a672&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://blog.hiphipjorge.com/tutorial-building-a-realtime-image-sharing-app/"
			"https://semaphoreci.com/community/tutorials/getting-started-with-node-js-and-jasmine"
			"http://www.sys-con.com/node/3318327",
			"http://rancher.com/nodejs-mongodb-application-with-rancher-part-2/?utm_content=bufferf4a86&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"https://keymetrics.io/2015/03/26/pm2-clustering-made-easy/",
			"http://blog.npmjs.org/post/115305091285/introducing-the-npm-semantic-version-calculator"
			"http://www.sitepoint.com/6-nodejs-static-site-generators/"
			"http://code.tutsplus.com/articles/social-authentication-for-nodejs-apps-with-passport--cms-21618"
		],
		"FireBase":[
			"https://www.firebase.com/blog/2015-03-20-fireside-chat-testlio.html"
			"https://code4startup.com/projects/ninja-learn-angularjs-firebase-by-cloning-udemy"
			"https://www.youtube.com/watch?v=D-k0MeWdpao&list=PLT-DLWOBKbB6gEvXXbznfNY_opQonXMsk"
		],
		"Polymer":[
			"http://futurice.com/blog/declarative-apps-with-polymers-two-way-data-binding"
		]
		"StrongLoop":[
			"https://strongloop.com/strongblog/es6-variable-declarations/"
		]
		"iojs":[],
		"Express":[],
		"Sails":[
			"https://everystack.io/#!/catalog/components/sails"
		],
		"Ember":[
			"http://blog.yodersolutions.com/why-i-recommend-emberjs-over-angularjs/"
			"http://madhatted.com/2015/3/6/aligning-ember-js-with-web-standards-emberconf-2015"
			"http://www.sitepoint.com/twitter-authentication-ember-js-torii/"
		],
		"Hapijs":[
			"http://dailyjs.com/2015/03/16/hapijs-fullstack-stringformatter/"
		]
		"React":[
			"https://www.codementor.io/reactjs/tutorial"
			"https://scotch.io/tutorials/learning-react-getting-started-and-concepts"
			"http://tutorialzine.com/2014/07/5-practical-examples-for-learning-facebooks-react-framework/"
			"https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375"
			"http://www.bimeanalytics.com/engineering-blog/you-put-your-react-into-my-angular/"
			"https://facebook.github.io/react/blog/2015/03/19/building-the-facebook-news-feed-with-relay.html"
			"http://facebook.github.io/react/blog/2015/03/19/building-the-facebook-news-feed-with-relay.html"
			"http://swizec.com/reactd3js/"
			"https://www.airpair.com/javascript/posts/creating-container-components-part-1-shadow-dom"
			"http://blogs.atlassian.com/2014/08/flux-architecture-step-by-step/"
			"https://reactjsnews.com/getting-started-with-flux/"
			"https://github.com/RickWong/react-transmit"
			"http://blog.parse.com/2015/03/25/parse-and-react-shared-chemistry/"
			"http://adtmag.com/articles/2015/03/26/facebook-releases-react-native-for-building-native-mobile-apps-in-javascript.aspx"
			"http://brianpfeil.com/react-native-initial-thoughts/"
			"https://www.youtube.com/watch?v=X6YbAKiLCLU&list=PLb0IAmt7-GS1_7FcSupSJoUe21tF12eu8&index=1"
			"https://weluse.de/blog/first-impressions-on-react-native.html"
			"http://facebook.github.io/react/blog/2015/03/30/community-roundup-26.html"
			"http://www.raywenderlich.com/99473/introducing-react-native-building-apps-javascript"
			"http://www.syncano.com/getting-started-reactjs-tutorial/",
			"http://react-components.com/",
			"http://www.raywenderlich.com/99473/introducing-react-native-building-apps-javascript"
			"https://www.codementor.io/reactjs/tutorial/understanding-react-js-rendering"
			""
		],
		"BackBone":[
			"http://www.webcodegeeks.com/javascript/backbone-js/backbone-js-events-example/"
		],
		"Webrtc":[],
		"Ionic":[
			"http://devdactic.com/shrinking-headers-with-ionic/"
		],
		"Phonegap":[],
		"Knockout":[],
		"Jquery":[
			"http://dailyjs.com/2015/03/30/flowtype-jquery-frontend/"
		],
		"TYpeScript":[
			"https://www.airpair.com/typescript/posts/typescript-development-with-gulp-and-sublime-text"
		],
		"CofferScript":[],
		"ECMASCript":[
			"http://pouchdb.com/2015/03/05/taming-the-async-beast-with-es7.html"
			"http://derickbailey.com/2015/03/12/serially-iterating-an-array-asynchronously/"
			"http://www.2ality.com/2015/03/babel-on-node.html"
			"http://www.sitepoint.com/understanding-ecmascript-6-class-inheritance/"
			"http://babeljs.io/blog/2015/03/31/5.0.0/"
			"http://wiki.ecmascript.org/doku.php?id=harmony%3Aspecification_drafts#march_17_2015_rev_36_release_candidate_3"
			"http://tonyfreed.com/blog/top_javascript_interview_question_2015?utm_content=buffer7156a&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://www.2ality.com/2015/03/es6-generators.html"
			"http://raganwald.com/2015/04/01/partial-application.html"
		],
		"Meteor":[

			"https://www.meteor.com/blog/2015/03/17/meteor-104-mongo-cordova-template-subscriptions"
		],
		"Mean":[],
		"Other":[
			"http://codejets.com/javascript-best-practices-part-1/?utm_content=bufferddf18&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"https://javascriptweblog.wordpress.com/2015/01/05/if-hemingway-wrote-javascript-explained/?utm_content=buffer2cc1b&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://discourse.codecombat.com/t/javascript-this-vs-self/3143"
			"https://developers.google.com/v8/experiments"
			"http://www.sys-con.com/node/3313595"
			"https://twitter.com/gdi2290/status/578797776760385537"
			"https://everystack.io/#!/catalog/components/socketstream"
			"http://synaptic.juancazala.com/#/"
			"http://richardtier.com/2015/03/18/memoizing-ajax-requests-without-the-data-inconsistency/"
			"https://everystack.io/#!/catalog/components/noflo"
			"http://burakkanber.com/blog/machine-learning-full-text-search-in-javascript-relevance-scoring/"
			"http://www.infoq.com/news/2015/03/lodash-utility-library"
			"https://medium.com/@slsoftworks/javascript-world-domination-af9ca2ee5070"
			"http://www.webcodegeeks.com/javascript/dependency-injection-explained-via-javascript/?utm_content=bufferb31f9&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://www.infoworld.com/article/2901436/internet/faster-web-page-loading-without-javascript.html?phint=newt%3Dinfoworld_todays_blogs&phint=idg_eid%3D4b6859d3cf29bea2fdce1fcba704bf5e#tk.IFWNLE_nlt_blogs_2015-03-25"
			"http://blog.chromium.org/2015/03/new-javascript-techniques-for-rapid.html"
			"http://jakearchibald.com/2015/thats-so-fetch/"
			"https://developer.atlassian.com/blog/2015/03/i-keep-my-promises/"
			"https://developer.mozilla.org/en-US/Learn"
			"http://www.sitepoint.com/building-mobile-javascript-powered-audio-player/"
			"http://blog.bitovi.com/introducing-stealjs/"
			"http://www.conductor.com/nightlight/guide-publishing-javascript-open-source-projects/"
			"https://medium.com/clayallsopp/a-dynamic-crazy-native-mobile-future-powered-by-javascript-70f2d56b1987"
			"https://www.airpair.com/javascript/posts/unit-testing-ajax-requests-with-mocha"
			"http://tonyfreed.com/blog/introduction_to_fetch_api"
			"http://blog.webkid.io/javascript-chart-libraries/",
			"http://caspervonb.com/javascript/an-overview-of-javascript-in-2015-ecmascript-6/?utm_content=buffer8973b&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer",
			"http://educationware.net/exercism-io-become-a-better-programmer/"
			"https://everystack.io/#!/catalog/components/davis-js"
			"http://nicolaiarocci.com/new-releases-for-cerberus-and-eve/"
			"https://frontendmasters.com/courses/advanced-javascript/"
			"http://arasatasaygin.github.io/is.js/?utm_content=buffer06988&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
		]
	},