"Javascript":{
		"Angular":[
			"https://qconnewyork.com/workshop/introduction-angularjs"
			"http://blog.backand.com/time-saving-angularjs-tips"
			"http://blog.mgechev.com/2015/04/06/angular2-first-impressions/"
			"http://www.webcodegeeks.com/javascript/angular-js/angular-js-controller-example/"
			"http://thejackalofjavascript.com/getting-started-with-angular-2-0/"
			"http://www.webcodegeeks.com/javascript/angular-js/real-time-communication-angularjs-qorlate/"
			"http://www.webcodegeeks.com/javascript/angular-js/learning-angular-access-directive-scope-variables-from-directive-controllers-and-vice-versa/"
			"http://www.webcodegeeks.com/javascript/angular-js/angularjs-ui-router-components/"
			"http://www.knowarth.com/single-page-application-angular-js/"
			"http://www.webcodegeeks.com/javascript/angular-js/angular-not-single-page-web-apps/"
			"www.techtalky.com/modules-angular-js/"
			"http://www.webcodegeeks.com/javascript/angular-js/angularjs-borrow-concepts-jsf/"
			"http://java.dzone.com/articles/using-oauth-20-your-web"
			"http://blog.mgechev.com/2015/04/06/angular2-first-impressions/"
			"http://www.webcodegeeks.com/javascript/angular-js/angular-js-form-validation-example/"
			"http://code.tutsplus.com/tutorials/token-based-authentication-with-angularjs-nodejs--cms-22543"
			"http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support"
			"https://medium.com/@KamilLelonek/angularjs-and-scope-apply-best-practices-d07353175024"
			"https://medium.com/@tomastrajan/component-paradigm-cf32e94ba78b"
			"http://eisenbergeffect.bluespire.com/aurelia-angular-2-0-code-side-by-side-part-2/"
			"http://www.encodedna.com/angularjs/tutorial/format-text-using-angularjs-currency-filter.htm"
			"http://blog.crowdint.com/2015/03/18/angularjs-providers-under-the-hood.html"
			"http://www.htmlxprs.com/post/54/creating-a-super-simple-todo-app-using-angular-2-tutorial"
			"http://victorsavkin.com/post/114168430846/two-phases-of-angular-2-applications"
			"http://angularjs.blogspot.com/2015/03/forms-in-angular-2.html"
			"http://www.webcodegeeks.com/javascript/angular-js/interception-using-decorator-and-lazy-loading-with-angularjs"
			"https://www.airpair.com/angularjs/posts/ngmodeloptions-total-model-control"
			"http://www.jackyen.com/unit-test-a-controller-in-angularjs/"
			"https://angular.io/features.html"
			"https://stormpath.com/blog/angular-node-15-minutes/"
			"http://www.ciappara.com/2015/03/20/convert-json-object-from-angularjs-to-class-object-in-webapi/"
			"https://css-tricks.com/using-angularjs-for-data-visualisations/"
			"http://www.webcodegeeks.com/javascript/angular-js/angular-js-routing-example/"
			"http://www.jackyen.com/how-to-unit-test-an-angular-application-service-with-requests-to-backend/"
			"http://www.aurorasolutions.io/step-by-step-guide-to-configure-angular-routing-using-angular-route/"
			"http://www.aurorasolutions.io/angularjs-cross-component-communication/"
			"http://frontendcollisionblog.com/angular_init/",
			"https://www.airpair.com/angularjs/posts/angularjs-promises"
			"http://blog.ionic.io/angular-2-series-introduction/",
			"https://www.airpair.com/angularjs/posts/angularjs-promises"
			"https://medium.com/@TK_CodeBear/getting-started-with-angular-part-1-bd448458566e",
			"https://docs.google.com/document/d/1M9FmT05Q6qpsjgvH1XvCm840yn2eWEg0PMskSQz7k4E/preview?sle=true",
			"http://trendytechhub.blogspot.com/2015/02/how-to-build-single-page-application.html",
			"http://dailyjs.com/2015/03/31/angular-grid-react-native/",
			"https://devcenter.appery.io/tutorials/angularjs/bootstrap/",
			"http://jaysoo.ca/2015/03/30/container-component-pattern-in-angular-1/",
			"http://conceptf1.blogspot.com/p/learning-angularjs.html",
			"http://jpeyatt.com/angularjs-ui-bootstrap-modals/"
			"http://aakilfernandes.github.io/angular-scopelogger/"
			"http://www.webcodegeeks.com/javascript/angular-js/learning-angular-useful-utility-functions/"
			"http://victorsavkin.com/post/114050927521/two-phases-of-angular-2-applications"
			"http://www.zainabed.com/2015/03/angularjs-tutorials-bootstrap.html"
			"https://blog.codecentric.de/en/2015/03/five-ways-to-write-better-angular-services/"
			"http://www.angularjsbook.com/angular-basics/chapters/basics/"
			"http://www.pro-tekconsulting.com/blog/advancing-from-jquery-to-angularjs/"
			"https://blog.nraboy.com/2015/03/using-oauth-2-0-in-your-web-browser-with-angularjs/"
			"http://blog.carbonfive.com/2015/03/25/communication-between-collaborating-directives-in-angular/"
			"https://www.airpair.com/javascript/posts/build-a-realtime-sms-call-center-with-data-mcfly-and-twilio"
			"http://www.webcodegeeks.com/javascript/angular-js/learning-angular-set-language-culture-ui-displayed/"
			"https://medium.com/angularjs-meetup-south-london/angular-new-router-preview-8002340e5427"
			"https://github.com/swirlycheetah/generator-angular2"
			"http://blog.jhades.org/what-every-angular-project-likely-needs-and-a-gulp-build-to-provide-it/"
			"http://blog.mgechev.com/2015/03/09/build-learn-your-own-light-lightweight-angularjs/#hnhttp://blog.mgechev.com/2015/03/09/build-learn-your-own-light-lightweight-angularjs/#hn"
			"https://www.airpair.com/pubnub/posts/realtime-angularjs-pubsub-messaging-using-pubnub1"
			"http://blog.sodhanalibrary.com/2015/04/angularjs-directive-for-mouse-wheel.html"
		],
		"JXCore":[
			"http://www.goland.org/jxcore/"
		]


		"FireBase":[
			"https://www.firebase.com/blog/2015-04-10-realtime-maps-cartodb-firebase.html"
			"http://java.dzone.com/articles/sign-firebase-facebook-using"
			"https://www.firebase.com/docs/ios/examples.html"
			"https://www.firebase.com/blog/2015-03-20-fireside-chat-testlio.html"
			"https://code4startup.com/projects/ninja-learn-angularjs-firebase-by-cloning-udemy"
			"https://www.youtube.com/watch?v=D-k0MeWdpao&list=PLT-DLWOBKbB6gEvXXbznfNY_opQonXMsk"
		],
		"Polymer":[
			"http://futurice.com/blog/declarative-apps-with-polymers-two-way-data-binding"
		]
		"StrongLoop":[
			"https://strongloop.com/strongblog/node-js-process-manager-production-docker/"
			"https://strongloop.com/strongblog/es6-variable-declarations/"
		]
		"iojs":[
			"https://medium.com/node-js-javascript/io-js-week-of-april-3rd-a4e1fe0c38c1"
			"https://iojs.org/en/faq.html"
		],

		"Ember":[
			"http://emberjs.com/blog/2015/01/08/inside-fastboot-faking-the-dom-in-node.html"
			"http://blog.yodersolutions.com/why-i-recommend-emberjs-over-angularjs/"
			"http://madhatted.com/2015/3/6/aligning-ember-js-with-web-standards-emberconf-2015"
			"http://www.sitepoint.com/twitter-authentication-ember-js-torii/"
		],
		"Hapijs":[
			"http://rafaelcorral.com/blog/building-a-restful-api-in-node-using-hapi-js-8"
			"http://dailyjs.com/2015/03/16/hapijs-fullstack-stringformatter/"
		]

		"React":[
			"https://codepicnic.com/posts/a-quick-start-to-react-in-4-steps-i-a5e00132373a7031000fd987a3c9f87b/"
			"http://zippyui.github.io/react-datagrid/#/"
			"http://fluxxor.com/what-is-flux.html"
			"http://attackofzach.com/react-components-for-google-maps-part-2/"
			"http://blog.tryolabs.com/2015/04/07/react-examples-mailbox"
			"https://medium.com/@PhilPlckthun/react-to-this-nonsense-and-move-on-3d9f9111a77d"
			"http://react.parts/native-ios"
			"http://almostobsolete.net/react-native/custom-ios-views-with-react-native.html"
			"http://madscript.com/halogen/"
			"http://moduscreate.com/react_native_custom_components_ios/"
			"http://scotch.io/tutorials/javascript/build-a-real-time-twitter-stream-with-node-and-react-js"
			"https://www.codementor.io/reactjs/tutorial"
			"https://scotch.io/tutorials/learning-react-getting-started-and-concepts"
			"http://tutorialzine.com/2014/07/5-practical-examples-for-learning-facebooks-react-framework/"
			"https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375"
			"http://www.bimeanalytics.com/engineering-blog/you-put-your-react-into-my-angular/"
			"https://facebook.github.io/react/blog/2015/03/19/building-the-facebook-news-feed-with-relay.html"
			"http://facebook.github.io/react/blog/2015/03/19/building-the-facebook-news-feed-with-relay.html"
			"http://swizec.com/reactd3js/"
			"https://www.airpair.com/javascript/posts/creating-container-components-part-1-shadow-dom"
			"http://blogs.atlassian.com/2014/08/flux-architecture-step-by-step/"
			"https://reactjsnews.com/getting-started-with-flux/"
			"https://github.com/RickWong/react-transmit"
			"http://blog.parse.com/2015/03/25/parse-and-react-shared-chemistry/"
			"http://adtmag.com/articles/2015/03/26/facebook-releases-react-native-for-building-native-mobile-apps-in-javascript.aspx"
			"http://brianpfeil.com/react-native-initial-thoughts/"
			"https://www.youtube.com/watch?v=X6YbAKiLCLU&list=PLb0IAmt7-GS1_7FcSupSJoUe21tF12eu8&index=1"
			"https://weluse.de/blog/first-impressions-on-react-native.html"
			"http://facebook.github.io/react/blog/2015/03/30/community-roundup-26.html"
			"http://www.raywenderlich.com/99473/introducing-react-native-building-apps-javascript"
			"http://www.syncano.com/getting-started-reactjs-tutorial/",
			"http://react-components.com/",
			"http://www.raywenderlich.com/99473/introducing-react-native-building-apps-javascript"
			"https://www.codementor.io/reactjs/tutorial/understanding-react-js-rendering"
			"https://www.airpair.com/node.js/posts/nodejs-framework-comparison-express-koa-hapi"
		],

		"Express":[
			"http://webapplog.com/url-parameters-and-routing-in-express-js/"
			"https://stormpath.com/blog/build-nodejs-express-stormpath-app/%20weekly&utm_medium=email&utm_campaign=express%20tutorial"
			"https://blog.nraboy.com/2015/01/session-management-expressjs-web-application/"
			"http://mherman.org/blog/2015/01/31/local-authentication-with-passport-and-express-4/#.VNKnnfWsWIR"
			"http://nodejs.blog.br/2015/02/caching-views-redis-express-framework"
			"https://www.airpair.com/javascript/complete-expressjs-nodejs-mongodb-crud-skeleton"
		],
		"Sails":[
			"http://www.ultrasaurus.com/2015/01/getting-started-sailsjs/"
			"http://sanestack.com/"
			"https://www.digitalocean.com/community/tutorials/how-to-create-an-node-js-app-using-sails-js-on-an-ubuntu-vps"
			"https://everystack.io/#!/catalog/components/sails"
		],
		"Phantomjs":[
			"http://engineering.shapesecurity.com/2015/01/detecting-phantomjs-based-visitors.html"
		]
		"Cylon.js":[
			"http://cylonjs.com/blog/2015/04/08/cylon-1.0.0/"
		]
		"Nodejs":["http://www.javacodegeeks.com/2013/12/node-js-synchronous-and-asynchronous-functions.html"
			"http://www.sitepoint.com/build-node-js-powered-chatroom-web-app-connecting-websockets/"
			"http://www.sitepoint.com/build-node-js-powered-chatroom-web-app-chatroom-ui-bootstrap/"
			"http://www.mongodb.com/blog/post/introducing-version-40-mongoose-nodejs-odm"
			"http://www.sitepoint.com/building-recipe-search-site-angular-elasticsearch/"
			"http://www.sitepoint.com/build-node-js-powered-chatroom-web-app-getting-started/"
			"https://strongloop.com/strongblog/node-js-performance-heap-profiling-tip/"
			"https://strongloop.com/strongblog/node-js-performance-tip-of-the-week-memory-leak-diagnosis/"
			"http://www.nearform.com/nodecrunch/node-js-develop-debugging-techniques/"
			"http://blogs.ancestry.com/techroots/scaling-node-js-in-the-enterprise/"
			"http://www.robotlovesyou.com/bdd-tdd/"
			"http://code.tutsplus.com/tutorials/multi-instance-nodejs-app-in-paas-using-redis-pubsub--cms-22239"
			"https://medium.com/@Philmod/debugging-node-js-29b2097df36c"
			"http://blog.backand.com/github-webhook-node/"
			"http://www.sitepoint.com/basics-node-js-streams/"
			"https://stormpath.com/blog/everything-you-ever-wanted-to-know-about-node-dot-js-sessions/"
			"http://blog.risingstack.com/functional-reactive-programming-with-the-power-of-nodejs-streams/"
			"http://bites.goodeggs.com/posts/selenium-webdriver-nodejs-tutorial/"
			"http://tutorialzine.com/2015/01/your-first-node-webkit-app/"
			"http://psteeleidem.com/node-module-factory-pattern/"
			"https://nodesource.com/blog/understanding-the-nodejs-event-loop"
			"https://gist.github.com/hueniverse/a06f6315ea736ed1b46d"
			"http://nodejs.blog.br/2015/01/using-nodejs-with-mysql"
			"http://www.sitepoint.com/deploying-heroku-using-gulp-node-git/"
			"http://mherman.org/blog/2015/02/12/postgresql-and-nodejs/"
			"http://blog.robertonodi.me/managing-files-with-node-js-and-mongodb-gridfs/"
			"http://blog.justonepixel.com/geek/2015/02/15/batch-operations-writable-streams/"
			"http://www.datastax.com/dev/blog/nodejs-cassandra-javascript-type-support"
			"https://engineering.gosquared.com/optimise-node-http-server"
			"https://raygun.io/blog/2015/03/node-performance-hapi-express-js-restify/"
			"https://egghead.io/lessons/nodejs-first-api-with-node-js-express-and-mongodb"
			"https://strongloop.com/strongblog/nodejs-testing-documenting-apis-mocha-acquit/"
			"http://www.bennadel.com/blog/2797-creating-objects-with-a-null-prototype-in-node-js.htm"
			"http://rancher.com/building-a-nodejs-app-using-mongodb-and-rancher-part-1/"
			"http://vansande.org/2015/03/22/unit_testing_with_mocks_in_node_js"
			"https://sendgrid.com/docs/Utilities/code_workshop.html"
			"http://www.nearform.com/nodecrunch/node-js-develop-debugging-techniques/"
			"http://code.tutsplus.com/tutorials/nodejs-succinctly-arrays--cms-23291"
			"http://www.sitepoint.com/build-node-js-powered-chatroom-web-app-getting-started"
			"http://omarfouad.com/blog/2015/03/21/advanced-angularjs-structure-with-gulp-node-and-browserify/"
			"http://blog.hiphipjorge.com/tutorial-building-a-realtime-image-sharing-app/"
			"https://semaphoreci.com/community/tutorials/getting-started-with-node-js-and-jasmine"
			"http://www.sys-con.com/node/3318327",
			"https://www.airpair.com/node.js/posts/microservices-nodejs-containers"
			"http://www.sitepoint.com/getting-started-wintersmith-nodejs-static-site-generator/"
			"https://keymetrics.io/2015/03/26/pm2-clustering-made-easy/"
			"http://blog.ragingflame.co.za/2015/4/1/how-i-build-nodejs-applications"
			"http://rancher.com/nodejs-mongodb-application-with-rancher-part-2/"
			"https://keymetrics.io/2015/03/26/pm2-clustering-made-easy/",
			"http://blog.npmjs.org/post/115305091285/introducing-the-npm-semantic-version-calculator"
			"http://www.sitepoint.com/6-nodejs-static-site-generators/"
			"http://code.tutsplus.com/articles/social-authentication-for-nodejs-apps-with-passport--cms-21618"
		],
		"Socketio":[
			"http://www.giacomovacca.com/2015/02/websockets-over-nodejs-from-plain-to.html"
			"http://tutorialzine.com/2015/02/smartphone-remote-control-for-presentations/"
			"http://knowthen.com/episode-10-building-realtime-applications-just-got-easy/"
		]
		"BackBone":[

			"https://code.mixpanel.com/2015/04/08/straightening-our-backbone-a-lesson-in-event-driven-ui-development/"
			"http://www.webcodegeeks.com/javascript/backbone-js/backbone-js-events-example/"
		],
		"Webrtc":[
			"http://sdelements.github.io/lets-chat/"
			"http://thejackalofjavascript.com/node-webkit-webrtc-and-angularjs-a-video-chat-client/"
		],
		"Ionic":[
			"http://www.gajotres.net/storing-data-in-ionic-framework-and-onsenui/"
			"http://java.dzone.com/articles/using-mobilefirst-sql-adapters"
			"http://thejackalofjavascript.com/ionic-twilio-and-node-scheduler-part-1/"
			"http://www.webspeaks.in/2015/03/html5-offline-mobile-app-using-ionic-pouchdb.html"
			"http://devdactic.com/shrinking-headers-with-ionic/"
		],
		"Phonegap":[],
		"Knockout":[],
		"Jquery":[
			"http://java.dzone.com/articles/packaging-jquery-mobile"
			"http://genius.it/ejohn.org/blog/annotated-version-of-the-original-jquery-release/"
			"http://dailyjs.com/2015/03/30/flowtype-jquery-frontend/"
			"http://www.webcodegeeks.com/javascript/jquery/jquery-dialog-example/"
		],
		"TYpeScript":[
			"http://blog.mgechev.com/2015/04/06/angular2-first-impressions/"
					"http://cacodaemon.de/index.php?id=67
			"http://www.infoq.com/news/2015/04/typescript-1-5"
			"https://www.airpair.com/typescript/posts/typescript-development-with-gulp-and-sublime-text"
		],
		"CofferScript":[
			"http://www.developwithpurpose.com/coffeescript-is-dead-long-live-coffeescript/"
		],
		"Gulp":[
			"http://www.angularonrails.com/how-to-wire-up-ruby-on-rails-and-angularjs-as-a-single-page-application-gulp-version/"
		]
		"ECMASCript":[
			"http://www.2ality.com/2015/04/deploying-es6.html"
			"http://www.noupe.com/development/understanding-ecmascript-6-class-and-inheritance-90966.html"
			"http://www.2ality.com/2015/04/node-es6-transpiled.html"
			"http://www.ifwe.co/code/posts/easing-the-transition-to-es6/"
			"http://www.sitepoint.com/simplifying-asynchronous-coding-es7-async-functions/"
			"http://tech.pro/blog/6742/callback-to-future-functor-applicative-monad"
			"http://es6-features.org/"
			"http://www.2ality.com/2015/04/webpack-es6.html"
			"http://raganwald.com/2015/04/01/partial-application.html"
			"http://schempy.com/async_tasks_with_es6_generators"
			"http://pouchdb.com/2015/03/05/taming-the-async-beast-with-es7.html"
			"http://derickbailey.com/2015/03/12/serially-iterating-an-array-asynchronously/"
			"http://www.2ality.com/2015/03/babel-on-node.html"
			"http://www.sitepoint.com/understanding-ecmascript-6-class-inheritance/"
			"http://babeljs.io/blog/2015/03/31/5.0.0/"
			"http://wiki.ecmascript.org/doku.php?id=harmony%3Aspecification_drafts#march_17_2015_rev_36_release_candidate_3"
			"http://tonyfreed.com/blog/top_javascript_interview_question_2015"
			"http://www.2ality.com/2015/03/es6-generators.html"
		],
		"D3":[
			"http://www.datavizualization.com/blog/d3-data-visualizations-case-study-apple-patents"
		]
		"Meteor":[
			"http://dataconomy.com/meteor-unleashes-1-1-allowing-one-codebase-for-windows-os-x-and-linux/"
			"https://www.youtube.com/watch?v=-QtrkXKvQFc&feature=youtu.be&list=PLTUf4ytkmI8Q3mSRIrkPfjkERTxHopzKG"
			"http://docs.meteor.com/#/full/blaze_render"
			"http://blog.percolatestudio.com/engineering/reactive-user-interfaces/"
			"https://medium.com/@stubailo/data-flow-from-the-database-to-the-ui-three-layers-of-meteor-d5e208b466c3"
			"http://blog.differential.com/this-week-in-meteor-8/"
			"https://www.youtube.com/watch?v=akWn_WD2cyA"
			"http://joshowens.me/getting-started-with-meteor-js/"
			"https://www.meteor.com/blog/2015/03/17/meteor-104-mongo-cordova-template-subscriptions"
		],
		"Mean":[
			"https://hackhands.com/how-to-get-started-on-the-mean-stack/"
		],
		"Other":[
			"http://jlongster.com/Stop-Trying-to-Catch-Me"
			"http://examples.javacodegeeks.com/enterprise-java/rest/resteasy/json-example-with-resteasy-jackson/"
			"http://www.webcodegeeks.com/javascript/javascript-promises-essentials/"
			"http://www.json2yaml.com/"
			"http://www.sitepoint.com/simple-inheritance-javascript/"
			"https://medium.com/@jyotiska/json-vs-simplejson-vs-ujson-a115a63a9e26"
			"http://codejets.com/javascript-best-practices-part-1/"
			"https://javascriptweblog.wordpress.com/2015/01/05/if-hemingway-wrote-javascript-explained/"
			"http://discourse.codecombat.com/t/javascript-this-vs-self/3143"
			"https://developers.google.com/v8/experiments"
			"http://www.sys-con.com/node/3313595"
			"https://twitter.com/gdi2290/status/578797776760385537"
			"https://everystack.io/#!/catalog/components/socketstream"
			"http://synaptic.juancazala.com/#/"
			"http://richardtier.com/2015/03/18/memoizing-ajax-requests-without-the-data-inconsistency/"
			"https://everystack.io/#!/catalog/components/noflo"
			"http://burakkanber.com/blog/machine-learning-full-text-search-in-javascript-relevance-scoring/"
			"http://www.infoq.com/news/2015/03/lodash-utility-library"
			"https://medium.com/@slsoftworks/javascript-world-domination-af9ca2ee5070"
			"http://www.webcodegeeks.com/javascript/dependency-injection-explained-via-javascript/"
			"http://www.infoworld.com/article/2901436/internet/faster-web-page-loading-without-javascript.html?phint=newt%3Dinfoworld_todays_blogs&phint=idg_eid%3D4b6859d3cf29bea2fdce1fcba704bf5e#tk.IFWNLE_nlt_blogs_2015-03-25"
			"http://blog.chromium.org/2015/03/new-javascript-techniques-for-rapid.html"
			"http://jakearchibald.com/2015/thats-so-fetch/"
			"https://developer.atlassian.com/blog/2015/03/i-keep-my-promises/"
			"https://developer.mozilla.org/en-US/Learn"
			"http://www.sitepoint.com/building-mobile-javascript-powered-audio-player/"
			"http://blog.bitovi.com/introducing-stealjs/"
			"http://www.conductor.com/nightlight/guide-publishing-javascript-open-source-projects/"
			"https://medium.com/clayallsopp/a-dynamic-crazy-native-mobile-future-powered-by-javascript-70f2d56b1987"
			"https://www.airpair.com/javascript/posts/unit-testing-ajax-requests-with-mocha"
			"http://tonyfreed.com/blog/introduction_to_fetch_api"
			"http://blog.webkid.io/javascript-chart-libraries/",
			"http://caspervonb.com/javascript/an-overview-of-javascript-in-2015-ecmascript-6/",
			"http://educationware.net/exercism-io-become-a-better-programmer/"
			"https://everystack.io/#!/catalog/components/davis-js"
			"http://nicolaiarocci.com/new-releases-for-cerberus-and-eve/"
			"https://frontendmasters.com/courses/advanced-javascript/"
			"http://arasatasaygin.github.io/is.js/"
			"http://www.objectplayground.com"
			"https://www.twilio.com/blog/2015/03/create-a-browser-based-photobooth-with-javascript-php-and-twilio.html"
		],
		"Compiler&Interpyer":[
			"http://howjs.com/zFiG/2"
		]
	}