"Network":[
	"https://rtcamp.com/tutorials/benchmark/httperf/",
	"http://piotrkarny.com/blog/2012/07/29/httperf-problems/",
	"http://daniel.haxx.se/blog/2015/03/31/the-state-and-rate-of-http2-adoption/",
	"https://ask.fedoraproject.org/en/question/8231/how-to-enable-a-port-in-firewall/",
	"http://www.cyberciti.biz/faq/howto-rhel-linux-open-port-using-iptables/",
	"https://fedoraproject.org/wiki/How_to_edit_iptables_rules",
	"http://sites.inka.de/~W1011/devel/tcp-tcp.html"
	"http://www.sajalkayan.com/post/http2-wordcount.html"
	"http://daniel.haxx.se/blog/2015/03/06/tls-in-http2/"
	"https://www.logintc.com/blog/2015-04-08-LoginTC-Chrome-2-factor-for-desktops.html"
	"http://techcrunch.com/2015/04/07/introducing-the-tc-network-and-editorial-calendar/"
	"https://www.youtube.com/watch?v=SF9BFf0mL4E&utm_content=bufferf2f10&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
]