"Other":{
		"http://developerblog.redhat.com/2015/04/07/jit-compilation-using-gcc-5-2/"
		"http://www.sitepoint.com/web-designers-guide-to-programming/"
		"http://lambda-nights.com/"
		"1":"http://code.tutsplus.com/tutorials/codeship-continuous-integration-and-delivery-made-simple--cms-23517",
		"2":"https://www.paypal-engineering.com/2015/03/17/introducing-support/",
		"3":"http://boxesandarrows.com/a-beginners-guide-to-web-site-optimization-part-1/",
		"":"http://tom-lord.weebly.com/blog/reverse-engineering-regular-expressions",
		"http://makethisinanhour.com/",
		"http://school.looprecur.com/"
		"http://hyperpolyglot.org/"
		"http://www.tonymarston.net/php-mysql/dependency-injection-is-evil.html"
		"http://www.javacodegeeks.com/2014/01/9-technologies-to-be-discussed-in-2014.html"
		"http://www.javacodegeeks.com/2014/01/wtf-is-an-architect-anyway.html"
		"http://www.sitepoint.com/client-testimonials/"
		"http://boundary2.org/2015/03/25/artificial-intelligence-as-alien-intelligence/"
		"http://www.javacodegeeks.com/2015/04/5-simple-rules-for-securely-storing-passwords.html"
		"http://www.infoq.com/news/2015/03/uber-realtime-market-platform"
		"https://everystack.io/#!/catalog/components/ratchet"
		"https://ngrok.com/?v=2"
		
		"http://paginas.fe.up.pt/~prodei/dsie12/papers/paper_17.pdf"
		"http://www.bloomberg.com/company/2015-03-24/bloomberg-weve-made-brisket-can-make-anything/"
		"http://www.infoq.com/news/2015/03/uber-realtime-market-platform+news&utm_campaign=calendar"
		"4":"https://www.atlassian.com/webinar-registration/jira-agile/stress-free-release-free-release-webinar"
		"http://www.bigdatanews.com/group/bdn-daily-press-releases/forum/topics/varnish-software-releases-varnish-api-engine"
	}