"Python":{
		"Flask":[
			"http://tutsbucket.com/tutorials/building-a-blog-using-flask-and-angularjs-part-1/?utm_content=bufferffe6a&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://techstonia.github.io/twilio-voice-blog.html?utm_content=buffer519ba&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://www.matthieuamiguet.ch/blog/synchronize-clients-flask-application-websockets?utm_content=buffer09247&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"https://realpython.com/blog/python/the-ultimate-flask-front-end/"
			"https://realpython.com/blog/python/the-ultimate-flask-front-end/?utm_content=buffer7ead2&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer#.VP2fV1lXx-Y.reddit"
		],
		"Django":[
			"http://za.github.io/2015/03/18/melb-django-dequorum/"
			"http://www.lexev.org/en/2015/debug-sql-django-test/?utm_content=bufferfca7f&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://www.caktusgroup.com/blog/2015/03/20/astro-code-school-now-accepting-applications-intermediate-django-python/"
			"http://djangowos.com/?utm_content=buffer6d679&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://code.tutsplus.com/tutorials/building-rest-apis-using-eve--cms-22961?utm_content=bufferf9126&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://www.maxburstein.com/blog/realtime-django-using-nodejs-and-socketio/",
			"https://syerram.silvrback.com/make-django-fasssst"
			"http://lukeplant.me.uk/blog/posts/my-approach-to-class-based-views/"
			"https://coderwall.com/p/mwhmfg/posting-from-angular-to-django"
			"http://www.willmcgugan.com/blog/tech/2015/3/14/saving-processes-and-threads-in-a-wsgi-server/"
			"https://realpython.com/blog/python/api-integration-in-python/?utm_content=bufferb0e3a&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer#.VPXPZ1WlN0c.reddit"
		],
		"Pyramid":[
			"http://davidemoro.blogspot.com/2015/03/kotti-cms-events-insert-subobjects.html?utm_source=twitterfeed&utm_medium=twitter"
			"https://everystack.io/#!/catalog/components/pyramid"
		],
		"Data":[
			"http://engineering.bloomreach.com/briefly-python-dsl-scale-mapreduce-pipelines/?utm_content=buffer45256&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://blog.dscpl.com.au/2015/03/using-wrapt-to-support-testing-of.html"
			"http://kachkach.com/data-processing-and-machine-learning-with-python/?utm_content=buffer72b45&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://glowingpython.blogspot.com/2014/08/quick-hdf5-with-pandas.html"
			"http://lqdc.github.io/modeling-zero-day-malware-spread.html?utm_content=bufferced36&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://desilinguist.org/pdf/crossroads.pdf?utm_content=buffer6dc1f&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://kachkach.com/data-processing-and-machine-learning-with-python/?utm_content=buffer49b7c&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://dataconomy.com/14-best-python-pandas-features/"
			"http://kukuruku.co/hub/python/introduction-to-machine-learning-with-python-andscikit-learn?utm_content=buffer70870&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://matthewrocklin.com/blog/work/2015/03/16/Fast-Serialization/?utm_content=buffer27735&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
		],
		"Zope":[
			"http://docs.zope.org/zope2/releases/2.12/INSTALL.html"
		]
		"Raspberry":[
			"http://matthewkwilliams.com/index.php/2015/03/21/swarming-raspberry-pi-part-1/"
			"http://matthewkwilliams.com/index.php/2015/03/29/swarming-raspberry-pi-part-2-registry-mirror/"
		]
		"Others":[
			"http://www.cubicweb.org/blogentry/5040318?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+cubicweborg+%28CubicWeb%27s+Blog%29"
			"http://xonsh.org/tutorial.html"
			"http://blog.gmludo.eu/2015/03/benchmark-python-web-production-stack.html"
			"https://www.codementor.io/python/tutorial/introduction-to-decorators#/.VQH-7svGWQk.twitter"
			"https://github.com/rothnic/anaconda-notebook?utm_content=buffera7d87&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"https://zato.io/blog/posts/hot-deploy-api-service.html"
			"http://pedrorodriguez.io/2015/03/14/chain-functional-programming-in-python-2/"
			"http://crossbar.io/"
			"https://github.com/hawkowl/crossbar"
			"https://github.com/tavendo"
			"http://tavendo.com/blog/post/is-crossbar-the-future-of-python-web-apps/"
			"https://glyph.twistedmatrix.com/2015/03/docker-deploy-double-dutch.html?utm_content=buffer74487&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://blog.udacity.com/2015/03/step-by-step-guide-install-lamp-linux-apache-mysql-python-ubuntu.html?utm_content=buffer0ac4d&utm_medium=social&utm_source=twitter.com&utm_campaign=update"
			"http://blog.quantopian.com/markowitz-portfolio-optimization-2/?utm_content=bufferdf597&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"https://everystack.io/#!/catalog/components/tweepy"
			"http://lwn.net/Articles/635397/?utm_content=buffer98aa3&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://emptysqua.re/blog/pymongo-use-greenlets-followup/"
			"http://emptysqua.re/blog/pymongo-key-order/"
			"https://everystack.io/#!/catalog/components/pykka"
			"https://zato.io/blog/posts/apitest-start.html"
			"https://github.com/lord63/pyhipku?utm_content=bufferfb791&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://www.toptal.com/python/beginners-guide-to-concurrency-and-parallelism-in-python#trust-only-devoted-devs-now"
			"https://github.com/gi0baro/weppy"
			"http://calvinmetcalf.com/post/103640348393/no-i-didnt-use-the-web-crypto-api"
			"https://opensourcehacker.com/2015/03/27/testing-web-hook-http-api-callbacks-with-ngrok-in-python/?utm_source=twitterfeed&utm_medium=twitter"
			"http://www.giantflyingsaucer.com/blog/?p=5541&utm_content=bufferb9677&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"https://everystack.io/#!/catalog/components/pycassa"
			"http://asyncio.org/",
			"https://everystack.io/#!/catalog/components/bjoern"
			"http://jamesls.com/micro-optimizations-in-python-code-speeding-up-lookups.html?utm_content=buffer6c255&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://blog.workshape.io/python-vs-ruby-the-workshape-smackdown/"
			"http://blog.gmludo.eu/2015/02/macro-benchmark-with-django-flask-and-asyncio.html",
			"http://bits.citrusbyte.com/protecting-a-python-codebase/",
			"https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-248038"
			"http://davidemoro.blogspot.com/2015/04/how-to-choose-your-cms.html?utm_source=twitterfeed&utm_medium=twitter",
			"http://emptysqua.re/blog/response-to-asynchronous-python-and-databases/",
			"https://developer.rackspace.com/blog/deploying-jupyterhub-for-education/"
			"http://www.rdegges.com/why-i-love-basic-auth/"
			"http://www.fullstackpython.com/table-of-contents.html"
			"http://rajeevrastogi.blogspot.com/2015/03/index-scan-optimization-for-condition.html"
			"http://dataconomy.com/linear-regression-implementation-in-python/?utm_content=buffer817d2&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://pydev.blogspot.ca/2015/02/design-for-client-side-applications-in.html?utm_content=buffer559c8&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://blog.ionelmc.ro/2015/02/09/understanding-python-metaclasses/?utm_content=buffer828e5&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
			"http://nedbatchelder.com/blog/201503/finding_temp_file_creators.html?utm_content=buffer86ee0&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"
		],
	},